AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS-SDK-Layer

Resources:
  AWSSDKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: aws-sdk
        Description: aws-sdk | aws-xray | uuid | use at your own risk
        ContentUri: layer/
        CompatibleRuntimes:
          - nodejs8.10
          - nodejs10.x
        LicenseInfo: 'MIT'
        RetentionPolicy: Retain

  AWSSDKLayerPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref AWSSDKLayer
      Principal: '*'